### ISSUE TITLE
Unable to obtain trial license to try GameDriver

### ISSUE THREAD

**Issue by WarrenLFR** [GameDriver-io/gdio.unreal_api.doc#8]
Hi, I am unsure if this is the right channel to request for this. I have tried multiple times signing up for the trial license, but I can't get an email with the license after registering. I used the chatting tool on the gamedriver website asking multiple questions as well but did not get any response. Could I get advice on how to proceed with this?

Regards,
Warren

**Comment by gd-evans** [comment]
Hi @WarrenLFR. I've emailed you regarding this and your questions to our website chat. Please let me know there is you have any other questions or concerns.
